name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Start services
        run: docker compose up -d -t 0 clickhouse
      - name: Install chproxy
        run: |
          wget https://github.com/ContentSquare/chproxy/releases/download/v1.16.0/chproxy_1.16.0_linux_amd64.tar.gz
          tar xf chproxy_1.16.0_linux_amd64.tar.gz
          sudo mv chproxy /usr/bin/chproxy
      - name: Install package
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=guesthouse --cov-report=xml
      - uses: codecov/codecov-action@v3

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.actor != 'dependabot[bot]' }}
